openapi: 3.1.0
info:
  title: Product API
  description: Read-only API for product catalog, pricing, and availability.
  version: "1.0"
servers:
- url: http://localhost:8080/product/v1
  description: Generated server url
paths:
  /prices/{id}:
    get:
      tags:
      - price-controller
      summary: Get price by product ID
      description: Retrieve the price details for a specific product by its ID.
      operationId: getPrice
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved price
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PriceResponse"
        "404":
          description: Product not found
  /items/{id}:
    get:
      tags:
      - item-controller
      summary: Get the product details by ID
      description: "Returns the information about the product for the provided item-id.\
        \ Like description, barcode, etc."
      operationId: getItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "404":
          description: Item information is not available
  /health:
    get:
      tags:
      - health-controller
      summary: Get health status
      description: Returns the health status of the application.
      operationId: healthCheck
      responses:
        "200":
          description: Successfully retrieved health status
          content:
            '*/*':
              schema:
                type: string
  /availability/{id}:
    get:
      tags:
      - availability-controller
      summary: Get availability by product ID
      description: Returns the available units along with threshold quantities for
        any provided item-id.
      operationId: getAvailability
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully retrieved availability
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvailabilityResponse"
        "404":
          description: Availability information is not available
  /error:
    get:
      tags:
      - custom-error-controller
      operationId: handleError
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    put:
      tags:
      - custom-error-controller
      operationId: handleError_2
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    post:
      tags:
      - custom-error-controller
      operationId: handleError_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    delete:
      tags:
      - custom-error-controller
      operationId: handleError_3
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    options:
      tags:
      - custom-error-controller
      operationId: handleError_6
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    head:
      tags:
      - custom-error-controller
      operationId: handleError_5
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
    patch:
      tags:
      - custom-error-controller
      operationId: handleError_4
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        product_id:
          type: string
        regular_price:
          type: number
        sale_price:
          type: number
        price_type:
          type: string
    ImageData:
      type: object
      properties:
        primary_image:
          type: string
        alternate_image:
          type: string
        base_url:
          type: string
    ItemResponse:
      type: object
      properties:
        item_id:
          type: string
        small_description:
          type: string
        long_description:
          type: string
        category:
          type: string
        merch_class:
          type: integer
          format: int32
        channel_restriction:
          type: string
        barcode:
          type: string
        brand_name:
          type: string
        age_restriction:
          type: integer
          format: int32
        image_data:
          $ref: "#/components/schemas/ImageData"
    AvailabilityResponse:
      type: object
      properties:
        product_id:
          type: string
        available_units:
          type: integer
          format: int32
        limited_quantity_threshold:
          type: integer
          format: int32
