services:
  product-api:
    build:
      context: product-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
  cart:
    build:
      context: cart-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      product-api:
        condition: service_healthy
