
### Health Check
GET http://localhost:8080/retail_data_services/v1/actuator/health

### Open API (json)
GET http://localhost:8080/retail_data_services/v1/api-docs
Content-Type: application/json

### Open API (yml)
GET http://localhost:8080/retail_data_services/v1/api-docs.yaml

###  Get Item List
GET http://localhost:8080/retail_data_services/v1/items
Content-Type: application/json

###  Filter Item List by Small Description
GET http://localhost:8080/retail_data_services/v1/items?small_description=jersey
Content-Type: application/json

###  Get Item
GET http://localhost:8080/retail_data_services/v1/items/123456
Content-Type: application/json

### Get Price
GET http://localhost:8080/retail_data_services/v1/prices/123456
Content-Type: application/json

### Get Availability
GET http://localhost:8080/retail_data_services/v1/availability/123456
Content-Type: application/json
