spring:
  main:
    lazy-initialization: true
  jmx:
    enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /docs
  swagger-ui:
    enabled: true

price:
  data-file: /data/prices.csv
  fast-change-prefix: "9012"

availability:
  data-file: /data/availability.csv
  fast-change-prefix: "9012"

item:
  data-file: /data/items.csv

behaviors:
  random-failing:
    failure-rate: 0.5
  slow-response:
    min-delay-ms: 1000
    max-delay-ms: 5000
